### PR TITLE
Multiple fixes to httpHeaders.py

### PR DESCRIPTION
**Pull request by nrathaus**
1. docstring
2. Remove unused import
3. Use sqlmap user_agents.txt file for expanded list of user agents

### CODE REVIEW

**Review by hansmach1ne — CHANGES_REQUESTED** [review]
Hey. Thanks for this PR. 

These are all good changes, however I don't think that loading a 4k lines of user agents into the array is a good idea, since only one will be picked if the user didn't specify the '--user-agent'. These 'pre-provided' user agents are just there to simulate the browser sending testing requests and it is not meant to be extensive list of all user-agents.

Could you remove the user-agents.txt and the code that handles it? Will push it afterwards

**Comment by nrathaus** [comment]
You want to not pick one from the list? 

Or just not keep it around the array? 

Or keep the small list of user agents you had before?

**Comment by hansmach1ne** [comment]
I'd prefer to keep the small list of user agents we had before.

**Comment by nrathaus** [comment]
I removed the `user-agents.txt` loading - I think the user agents you picked aren't ideal, I would go with current Firefox, Chrome and Safari user-agents, you can use:
https://www.whatismybrowser.com/guides/the-latest-user-agent/firefox
https://www.whatismybrowser.com/guides/the-latest-user-agent/safari
https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome

The idea of using current user-agent, is that it looks less suspicious than older outdated versions - and less likely to get blocked

**Pull request merged**
